akustik: Audio
Audio
Macros
#define AUDIO_TEST_DEV 0
Use Archived Audio Features.
#define DEFAULT_ATTEN 0.1
Default Attenuation.
#define I2S_BUFF_SIZE 512
I2S protocol buffer size.
#define I2S_HALF_SIZE ((I2S_BUFF_SIZE/2)-1)
Size of Half Buffer.
#define TOTAL_BUFF_SIZE I2S_BUFF_SIZE*16
Total buffer size.
#define TEST_DURATION 2
Global Duration for Testing.
Functions
void ht_audio_Init (void)
Initiate Audio driver via I2S.
void ht_audio_Zero (void)
Generate sine wave with only zero.
void ht_audio_Tone (double freq, double ampl)
Generate sine wave tone from halving formula with Frequency and Amplitude.
void ht_audio_Play (uint8_t duration)
Play Audio via I2S.
Variables
static uint16_t i2s_tx_buf [TOTAL_BUFF_SIZE]
I2S Transmit buffer.
static I2SConfig i2scfg
I2S Protocol config struct.
Detailed Description
Macro Definition Documentation
AUDIO_TEST_DEV
#define AUDIO_TEST_DEV 0
Use Archived Audio Features.
Definition at line 26 of file ht_audio.h.
DEFAULT_ATTEN
#define DEFAULT_ATTEN 0.1
Default Attenuation.
Hopes can reduce high freq noises
Definition at line 32 of file ht_audio.h.
I2S_BUFF_SIZE
#define I2S_BUFF_SIZE 512
I2S protocol buffer size.
If I2S-SPI and MMC-SPI use same DMA stream, set to 512. Please check DMA stream ID on both SPI peripherals.
Definition at line 39 of file ht_audio.h.
I2S_HALF_SIZE
#define I2S_HALF_SIZE ((I2S_BUFF_SIZE/2)-1)
Size of Half Buffer.
Definition at line 44 of file ht_audio.h.
TOTAL_BUFF_SIZE
#define TOTAL_BUFF_SIZE I2S_BUFF_SIZE*16
Total buffer size.
Just fill it below 44100
Definition at line 50 of file ht_audio.h.
TEST_DURATION
#define TEST_DURATION 2
Global Duration for Testing.
Definition at line 55 of file ht_audio.h.
Function Documentation
ht_audio_Init()
void ht_audio_Init (void)
Initiate Audio driver via I2S.
Definition at line 140 of file ht_audio.c.
ht_audio_Zero()
void ht_audio_Zero (void)
Generate sine wave with only zero.
Definition at line 146 of file ht_audio.c.
References i2s_tx_buf, and TOTAL_BUFF_SIZE.
Referenced by ht_audio_Tone(), and ThdFunc_ExtiCb().
ht_audio_Tone()
void ht_audio_Tone (double freq, double ampl)
Generate sine wave tone from halving formula with Frequency and Amplitude.
This function intended to be actual implementaion of sample preparation
Parameters
[in] Sine wave sample frequency in linear scaling from 400Hz (0.25,0.5,1,2,4,8,16,32) -> 500Hz=1.25
[in] Sine wave sample amplitude in linear scaling from 100dB (1 ~ 0.0001 or use ht_audio_Zero())
Definition at line 153 of file ht_audio.c.
References DEFAULT_ATTEN, ht_audio_Zero(), I2S_BUFF_SIZE, i2s_tx_buf, and i2scfg.
Referenced by cmd_max(), cmd_min(), cmd_tone(), and cmd_zero().
ht_audio_Play()
void ht_audio_Play (uint8_t duration)
Play Audio via I2S.
Play I2S Transmit buffer in loop
Parameters
[in] Duration to play in seconds
Definition at line 175 of file ht_audio.c.
References i2scfg.
Referenced by cmd_max(), cmd_min(), cmd_tone(), cmd_zero(), and ThdFunc_ExtiCb().
Variable Documentation
i2s_tx_buf
uint16_t i2s_tx_buf[TOTAL_BUFF_SIZE] static
I2S Transmit buffer.
Definition at line 125 of file ht_audio.c.
Referenced by ht_audio_Tone(), and ht_audio_Zero().
i2scfg
I2SConfig i2scfg static
Initial value:
= {
  i2s_tx_buf,
  NULL,
  I2S_BUFF_SIZE,
  NULL,
  0,
  16,
}
I2S Protocol config struct.
Definition at line 131 of file ht_audio.c.
Referenced by ht_audio_Play(), and ht_audio_Tone().