akustik: GPIO
GPIO
Functions
static ThdFunc_ExtiCb (thdExtiCb, arg)
Thread for Interrupt Callback.
static void extTestWave (EXTDriver *extp, expchannel_t channel)
Play Test EXTI Callback.
void ht_exti_Init (void)
External Interrupt Initialization.
static void indicator_m_off (void)
Set all Amplification/Frequency indicator LEDs to off.
static void indicator_m_on (uint8_t lednum)
Set Amplification/Frequency indicator LED.
static ThdFunc_Indicator (thdIndicator, arg)
Thread for Amplification/Frequency Level indicator.
void ht_led_Shift (void)
Shift Ampli/Freq status index by 1 level.
void ht_led_Init (void)
LED indicator initialization.
Variables
static uint8_t ext13 = 0
Interrupt 13 callback flag.
static const EXTConfig extcfg
External Interrupt Channel Config.
uint8_t idx_ampl
Amplification level status index.
uint8_t idx_freq
Frequency level status index.
Detailed Description
Function Documentation
ThdFunc_ExtiCb()
static ThdFunc_ExtiCb (thdExtiCb , arg) static
Thread for Interrupt Callback.
Reason: System freezed when call long process directly from Exti Callback
Definition at line 38 of file ht_exti.c.
References ext13, ht_audio_Play(), ht_audio_Zero(), ht_led_Shift(), and TEST_DURATION.
extTestWave()
static void extTestWave (EXTDriver * extp, expchannel_t channel) static
Play Test EXTI Callback.
Enumerated and not called directly by any normal thread
Only trigerring callback flag
Definition at line 58 of file ht_exti.c.
References ext13.
ht_exti_Init()
void ht_exti_Init (void)
External Interrupt Initialization.
Definition at line 96 of file ht_exti.c.
References extcfg.
indicator_m_off()
static void indicator_m_off (void) static
Set all Amplification/Frequency indicator LEDs to off.
Definition at line 38 of file ht_led.c.
Referenced by ThdFunc_Indicator().
indicator_m_on()
static void indicator_m_on (uint8_t lednum) static
Set Amplification/Frequency indicator LED.
LED to set on at desired number
Definition at line 53 of file ht_led.c.
ThdFunc_Indicator()
static ThdFunc_Indicator (thdIndicator , arg) static
Thread for Amplification/Frequency Level indicator.
Working by switching between Ampl and Freq LED indicator in microsecond
Definition at line 69 of file ht_led.c.
References indicator_m_off().
ht_led_Shift()
void ht_led_Shift (void)
Shift Ampli/Freq status index by 1 level.
Definition at line 88 of file ht_led.c.
References idx_ampl, and idx_freq.
Referenced by ThdFunc_ExtiCb().
ht_led_Init()
void ht_led_Init (void)
LED indicator initialization.
Definition at line 101 of file ht_led.c.
Variable Documentation
ext13
uint8_t ext13 = 0 static
Interrupt 13 callback flag.
Definition at line 30 of file ht_exti.c.
Referenced by extTestWave(), and ThdFunc_ExtiCb().
extcfg
const EXTConfig extcfg static
Initial value:
= {
  {
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_RISING_EDGE | EXT_MODE_GPIOC, extTestWave},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL},
    {EXT_CH_MODE_DISABLED, NULL}
  }
}
External Interrupt Channel Config.
Definition at line 68 of file ht_exti.c.
Referenced by ht_exti_Init().
idx_ampl
uint8_t idx_ampl
Amplification level status index.
Definition at line 28 of file ht_led.c.
Referenced by ht_led_Shift().
idx_freq
uint8_t idx_freq
Frequency level status index.
Definition at line 33 of file ht_led.c.
Referenced by ht_led_Shift().