akustik: Console
Console
Data Structures
struct ShellCommand
Custom command entry type.
struct ShellConfig
Shell descriptor type.
Macros
#define SHELL_ECHO FALSE
Enables Echo on Shell Console.
#define SHELL_PROMPT FALSE
Enables Prompt on Shell Console.
#define SHELL_WA_SIZE THD_WORKING_AREA_SIZE(1024)
Shell thread working area size.
#define SHELL_MAX_LINE_LENGTH 64
Shell maximum input line length.
#define SHELL_MAX_ARGUMENTS 4
Shell maximum arguments per command.
Typedefs
typedef void(* shellcmd_t) (BaseSequentialStream *chp, int argc, char *argv[])
Command handler function type.
Functions
static void cmd_test (BaseSequentialStream *chp, int argc, char *argv[])
Test command callback.
static void cmd_zero (BaseSequentialStream *chp, int argc, char *argv[])
Audio Zero command callback.
static void cmd_max (BaseSequentialStream *chp, int argc, char *argv[])
Audio Maximum command callback.
static void cmd_min (BaseSequentialStream *chp, int argc, char *argv[])
Audio Minimum command callback.
static void cmd_tone (BaseSequentialStream *chp, int argc, char *argv[])
Audio Play Halving-Formula with Frequency and Amplitude command callback.
void ht_comm_Init (void)
Start Shell and UART peripheral.
void ht_comm_ReInit (void)
Re-Initialize Shell Thread.
static THD_FUNCTION (shell_thread, p)
Shell thread function.
void shellInit (void)
Shell manager initialization.
void shellExit (msg_t msg)
Terminates the shell.
thread_t * shellCreateStatic (const ShellConfig *scp, void *wsp, size_t size, tprio_t prio)
Spawns a new shell.
bool shellGetLine (BaseSequentialStream *chp, char *line, unsigned size)
Reads a whole line from the input channel.
Variables
static thread_t * shelltp = NULL
Shell Console pointer.
static const ShellCommand commands []
Shell command and it's callback enumeration.
static const ShellConfig shell_cfg1
Shell Driver Config.
event_source_t shell_terminated
Shell termination event source.
static ShellCommand local_commands []
Array of the default commands.
event_source_t shell_terminated
Shell termination event source.
Detailed Description
Macro Definition Documentation
SHELL_ECHO
#define SHELL_ECHO FALSE
Enables Echo on Shell Console.
Definition at line 26 of file ht_console.h.
SHELL_PROMPT
#define SHELL_PROMPT FALSE
Enables Prompt on Shell Console.
Definition at line 31 of file ht_console.h.
SHELL_WA_SIZE
#define SHELL_WA_SIZE THD_WORKING_AREA_SIZE(1024)
Shell thread working area size.
Set to bigger size if necessary
Definition at line 37 of file ht_console.h.
SHELL_MAX_LINE_LENGTH
#define SHELL_MAX_LINE_LENGTH 64
Shell maximum input line length.
Definition at line 43 of file ht_console.h.
SHELL_MAX_ARGUMENTS
#define SHELL_MAX_ARGUMENTS 4
Shell maximum arguments per command.
Definition at line 50 of file ht_console.h.
Typedef Documentation
shellcmd_t
typedef void(* shellcmd_t) (BaseSequentialStream *chp, int argc, char *argv[])
Command handler function type.
Definition at line 56 of file ht_console.h.
Function Documentation
cmd_test()
static void cmd_test (BaseSequentialStream * chp, int argc, char * argv[]) static
Test command callback.
Enumerated and not called directly by any normal thread
Definition at line 40 of file ht_comm.c.
References SERIAL_BUFFERS_SIZE, and SERIAL_DEFAULT_BITRATE.
cmd_zero()
static void cmd_zero (BaseSequentialStream * chp, int argc, char * argv[]) static
Audio Zero command callback.
Enumerated and not called directly by any normal thread
Definition at line 51 of file ht_comm.c.
References ht_audio_Play(), ht_audio_Tone(), and TEST_DURATION.
cmd_max()
static void cmd_max (BaseSequentialStream * chp, int argc, char * argv[]) static
Audio Maximum command callback.
Enumerated and not called directly by any normal thread
Definition at line 65 of file ht_comm.c.
References ht_audio_Play(), ht_audio_Tone(), and TEST_DURATION.
cmd_min()
static void cmd_min (BaseSequentialStream * chp, int argc, char * argv[]) static
Audio Minimum command callback.
Enumerated and not called directly by any normal thread
Definition at line 88 of file ht_comm.c.
References ht_audio_Play(), ht_audio_Tone(), and TEST_DURATION.
cmd_tone()
static void cmd_tone (BaseSequentialStream * chp, int argc, char * argv[]) static
Audio Play Halving-Formula with Frequency and Amplitude command callback.
Enumerated and not called directly by any normal thread
Definition at line 102 of file ht_comm.c.
References ht_audio_Play(), ht_audio_Tone(), and TEST_DURATION.
ht_comm_Init()
void ht_comm_Init (void)
Start Shell and UART peripheral.
Serial Interface using UART0 (SD1)
Definition at line 225 of file ht_comm.c.
References shellInit().
ht_comm_ReInit()
void ht_comm_ReInit (void)
Re-Initialize Shell Thread.
This routine should be called on main thread with some delays
Definition at line 233 of file ht_comm.c.
References shell_cfg1, SHELL_WA_SIZE, and shelltp.
THD_FUNCTION()
static THD_FUNCTION (shell_thread , p) static
Shell thread function.
Parameters
[in] p pointer to a BaseSequentialStream object
Definition at line 121 of file ht_console.c.
References SHELL_MAX_ARGUMENTS, SHELL_MAX_LINE_LENGTH, and shellGetLine().
shellInit()
void shellInit (void)
Shell manager initialization.
@api
Definition at line 185 of file ht_console.c.
References shell_terminated.
Referenced by ht_comm_Init().
shellExit()
void shellExit (msg_t msg)
Terminates the shell.
Note
Must be invoked from the command handlers.
Does not return.
Parameters
[in] msg shell exit code
@api
Definition at line 199 of file ht_console.c.
References shell_terminated.
shellCreateStatic()
thread_t * shellCreateStatic (const ShellConfig * scp, void * wsp, size_t size, tprio_t prio)
Spawns a new shell.
Precondition
CH_CFG_USE_HEAP and CH_CFG_USE_DYNAMIC must be enabled.
Parameters
[in] scp pointer to a ShellConfig object
[in] size size of the shell working area to be allocated
[in] prio priority level for the new shell
Returns
A pointer to the shell thread.
Return values
NULL thread creation failed because memory allocation.
@apiCreate statically allocated shell thread.
Parameters
[in] scp pointer to a ShellConfig object
[in] wsp pointer to a working area dedicated to the shell thread stack
[in] size size of the shell working area
[in] prio priority level for the new shell
Returns
A pointer to the shell thread.
@api
Definition at line 238 of file ht_console.c.
shellGetLine()
bool shellGetLine (BaseSequentialStream * chp, char * line, unsigned size)
Reads a whole line from the input channel.
Parameters
[in] chp pointer to a BaseSequentialStream object
[in] line pointer to the line buffer
[in] size buffer maximum length
Returns
The operation status.
Return values
true the channel was reset or CTRL-D pressed.
false operation successful.
@api
Definition at line 256 of file ht_console.c.
Referenced by THD_FUNCTION().
Variable Documentation
shelltp
thread_t* shelltp = NULL static
Shell Console pointer.
Definition at line 34 of file ht_comm.c.
Referenced by ht_comm_ReInit().
commands
const ShellCommand commands[] static
Initial value:
= {
    {"test",cmd_test},
    {"zero",cmd_zero},
    {"tone",cmd_tone},
    {"max",cmd_max},
    {"min",cmd_min},
    {NULL, NULL}
}
Shell command and it's callback enumeration.
Extending from internal shell's callback
Definition at line 199 of file ht_comm.c.
shell_cfg1
const ShellConfig shell_cfg1 static
Initial value:
= {
  (BaseSequentialStream *)&SD1,
  commands
}
Shell Driver Config.
Serial Interface using UART0 (SD1)
Definition at line 220 of file ht_comm.c.
Referenced by ht_comm_ReInit().
shell_terminated [1/2]
event_source_t shell_terminated
Shell termination event source.
Definition at line 31 of file ht_console.c.
Referenced by shellExit(), and shellInit().
local_commands
ShellCommand local_commands[] static
Initial value:
= {
  {"info", cmd_info},
  {NULL, NULL}
}
Array of the default commands.
Definition at line 98 of file ht_console.c.
shell_terminated [2/2]
event_source_t shell_terminated
Shell termination event source.
Definition at line 31 of file ht_console.c.
Referenced by shellExit(), and shellInit().